name = "GeometricMachineLearning"
uuid = "194d25b2-d3f5-49f0-af24-c124f4aa80cc"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
julia = "1.6"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
