name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install imagemagick
          sudo apt-get install poppler-utils
          sudo apt-get install texlive-xetex
          sudo apt-get install texlive-science
          make all -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.build()
            Pkg.precompile()
            using Documenter: doctest
            using GeometricMachineLearning
            doctest(GeometricMachineLearning)'
          julia --project=docs docs/make.jl
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}