name: Documentation

on:
  push:
    branches:
      - main
      - documentation_for_optimizer_yaml_test
  pull_request:

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
      - run: |
          julia --project=docs/ -e '
              using Pkg
              Pkg.develop(PackageSpec(path=pwd()))
              Pkg.instantiate()
              Pkg.build()
              Pkg.precompile()'
          sudo apt-get install imagemagick
          sudo apt-get install poppler-utils
          sudo apt-get install texlive-xetex
          sudo apt-get install texlive-science
      - run: |
          make all -C docs/src/tikz
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using GeometricMachineLearning
            doctest(GeometricMachineLearning)'
      - run: julia --project docs/make.jl
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}