name: PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  LatexDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install imagemagick, poppler-utils and texlive
        run: |
            sudo apt-get install imagemagick
            sudo apt-get install poppler-utils
            sudo apt-get install texlive-xetex
            sudo apt-get install texlive-science
            sudo apt-get install latex-cjk-all
      - name: Make images
        run: make latex -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: install BrenierTwoFluid
        run: |
          cd docs
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' make install_brenier_two_fluid test_docs
          cd .. 
      - name: Make MNIST image
        run: make all -C docs/src/tutorials/mnist
      - name: make tex document
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs --color=yes --threads=2 docs/make.jl latex_output
      - name: Some sed magic 
        run: |
          make copy_png_files -C docs
          make put_figures_outside_of_minted_environment -C docs
          make do_correct_quotation_marks -C docs
          make make_correct_thrm_and_dfntn_and_xmpl_and_rmrk_and_proof_environment -C docs
          make references_instead_of_hyperlinks -C docs
          make correct_appendix -C docs
          make remove_home_part -C docs
          make remove_numbering_for_some_chapters -C docs
          make docstring_indexing -C docs
      - name: compile tex document
        run: |
          cd docs/build 
          xelatex -shell-escape GeometricMachineLearning.jl.tex
          xelatex -shell-escape GeometricMachineLearning.jl.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Docs in PDF version
          path: docs/build/GeometricMachineLearning.jl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}