name: PDF

on:
  push:
    branches:
      - main
      - make_mac_docs
      - volume_preserving_transformer
  pull_request:

jobs:
  LatexDocsUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install imagemagick
          sudo apt-get install poppler-utils
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          texlive_version: 2023
          run: |
            make pdf -C docs/src/tikz
      - run: | 
          make convert_with_pdftocairo -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
          # the following three lines do the same as calling `make.jl` with latex_output as input argument
          julia --project=docs --threads=2 docs/make.jl latex_output_no_pdf
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          texlive_version: 2023
          run: |
            tlmgr install preamble
            xelatex -shell-escape docs/build/GeometricMachineLearning.jl.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu-PDF
          path: GeometricMachineLearning.jl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LatexDocsMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make pdf -C docs/src/tikz
      - run: |
          make convert_with_sips -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
          # the following three lines do the same as calling `make.jl` with latex_output as input argument
          julia --project=docs --threads=2 docs/make.jl latex_output_no_pdf
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          texlive_version: 2023
          run: |
            xelatex -shell-escape docs/build/GeometricMachineLearning.jl.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Mac-PDF
          path: GeometricMachineLearning.jl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}