name: PDF

on:
  push:
    branches:
      - main
      - make_mac_docs
      - volume_preserving_transformer
  pull_request:

jobs:
  LatexDocsUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install imagemagick, poppler-utils and texlive
        run: |
          sudo apt-get install imagemagick
          sudo apt-get install poppler-utils
          wget --no-check-certificate https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat < install-tl-unx.tar.gz | tar xf -
          rm install-tl-unx.tar.gz
          cd install-tl-*
          sudo perl ./install-tl --no-interaction
          cd ..
          echo "/usr/local/texlive/2024/bin/x86_64-linux" >> $GITHUB_PATH
          tlmgr init-usertree
          # sudo tlmgr install preamble
      - run: |
          make linux -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
      - run: julia --project=docs --threads=2 docs/make.jl latex_output_no_pdf
      - run: xelatex -shell-escape docs/build/GeometricMachineLearning.jl.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu-PDF
          path: GeometricMachineLearning.jl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LatexDocsMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls /usr/local
      - run: wget --no-check-certificate https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
      - run: zcat < install-tl-unx.tar.gz | tar xf -
      - run: | 
          ls 
          rm install-tl-unx.tar.gz
      - run: | 
          cd install-tl-*
          sudo perl ./install-tl --no-interaction
          cd ..
      - run: ls /usr/local/texlive/2024/bin/universal-darwin
      - run: |
          echo "/usr/local/texlive/2024/bin/universal-darwin" >> $GITHUB_PATH
      - run: |
          tlmgr init-usertree
      - run: |
          make mac -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
      - run: julia --project=docs --threads=2 docs/make.jl latex_output_no_pdf
      - run: xelatex -shell-escape docs/build/GeometricMachineLearning.jl.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Mac-PDF
          path: GeometricMachineLearning.jl.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}