name: PDF

on:
  push:
    branches:
      - main
      - make_mac_docs
      - volume_preserving_transformer
  pull_request:

jobs:
  LatexDocsUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            sudo apt-get install imagemagick
            sudo apt-get install poppler-utils
            make linux -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
          # the following three lines do the same as calling `make.jl` with latex_output as input argument
          julia --project=docs docs/make.jl latex_output_no_pdf
          cd docs/build
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            pip3 install pygments
            xelatex -shell-escape GeometricMachineLearning.jl.tex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LatexDocsMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip3 install pygments
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make mac -C docs/src/tikz
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - run: |
          cd docs
          make install_brenier_two_fluid test_docs
          cd .. 
          # the following three lines do the same as calling `make.jl` with latex_output as input argument
          julia --project=docs docs/make.jl latex_output_no_pdf
          cd docs/build
      - run: |
          xelatex -shell-escape GeometricMachineLearning.jl.tex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}